# Generated by Django 5.0.2 on 2024-02-24 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixaAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='todosProdutos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.SmallIntegerField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caixaAPP.produto')),
            ],
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='produtos',
            field=models.ManyToManyField(to='caixaAPP.todosprodutos'),
        ),
    ]
