# Generated by Django 5.0.2 on 2024-03-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixaAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='quantidade',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='itens_venda',
            field=models.ManyToManyField(related_name='itensvendas_vendas', to='caixaAPP.itemvenda'),
        ),
    ]
