# Generated by Django 5.0.2 on 2024-03-24 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixaAPP', '0002_itemvenda_quantidade_alter_venda_itens_venda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='itens_venda',
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='venda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas_itensvendas', to='caixaAPP.venda'),
        ),
    ]
