# Generated by Django 5.0.2 on 2024-02-24 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caixaAPP', '0002_todosprodutos_alter_carrinho_produtos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todosprodutos',
            name='qtd',
        ),
    ]
