# Generated by Django 5.0.2 on 2024-02-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixaAPP', '0003_remove_todosprodutos_qtd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='produtos',
            field=models.ManyToManyField(to='caixaAPP.produto'),
        ),
        migrations.DeleteModel(
            name='todosProdutos',
        ),
    ]
